### ISSUE TITLE
Error when i use runShepherdSegmentation

### ISSUE THREAD

**Issue by Atumyugi** [remotesensinginfo/rsgislib#19]
input = r"xxx.tif"
output = r"xxxx.kea"

segutils.runShepherdSegmentation(input,output,gdalformat='KEA')

_segmentation.error: Could not create GDALDataset'

how can i fix this error,thank you!!!

**Comment by petebunting** [comment]
I would guess that the output path does not exist but without more information such as the whole stack output, I cannot comment further.

**Comment by Atumyugi** [comment]
> I would guess that the output path does not exist but without more information such as the whole stack output, I cannot comment further.

thanks for your reply, the more stack ouput as follows:

input = r"X:\18_pp\test.tif"
output = r"X:\18_pp\testSeg.tif"  (.kea is same erropr)
segutils.runShepherdSegmentation(input,output,gdalformat='KEA')

and the cmd information as follows:
Relabel clumps.
Opening clumps file: .\test_clump_elim.kea
Processing using Disk
ERROR 4: Attempt to create 'X:\18_pp\testSeg.tif' failed. Error: H5Fcreate failed 

Traceback (most recent call last):
File "E:/Project/segUtils/HelloShepherd.py", line 18. in <module>
 segutils.runShepherdSegmentation(input,output,gdalformat='KEA')
File "C:\ProgramData\Anaconda3\envs\torch\lib\site-packages\rsgislib\segmentation\segutils.py" line 188, in runShepherdSegmentation rsgislib.segmentation.relabelClumps(elimClumpsFile, outputClumps, gdalformat, processInMem)
_segmentation.error: Could not create GDALDataset.

**Comment by Atumyugi** [comment]
> I would guess that the output path does not exist but without more information such as the whole stack output, I cannot comment further.

and i can get a lot intermediate file, but cannot running relabel

**Comment by Atumyugi** [comment]
I solved this problem when I reinstalled the osgeo Lib, the relabel problem may lie in different dependent gdal libraries

**Comment by petebunting** [comment]
Glad you were able to solve the problem. We'll be releasing RSGISLib v5 before too long so I'll double check the code to see if I can see anything which might have caused this issue to occur.

**Comment by Atumyugi** [comment]
> Glad you were able to solve the problem. We'll be releasing RSGISLib v5 before too long so I'll double check the code to see if I can see anything which might have caused this issue to occur.

Okay, I will try to use your V5 version then, thank you for your team’s update
