### ISSUE TITLE
Question for segment a particularly large remote sensing image

### ISSUE THREAD

**Issue by Atumyugi** [remotesensinginfo/rsgislib#20]
I would like to ask, if I want to segment a particularly large remote sensing image, how do I use rsgislib to segment the remote sensing image and there is no obvious boundary feature after merging

**Comment by nmt28** [comment]
RSGISLib has a function in V4 called "performTiledSegmentation". You can use this to do a tiled segmentation of an image. This will be renamed perform_tiled_segmentation in V5 (not yet released)

**Comment by CesarAugusto88** [comment]
I would like to know if there is a possibility to add the confusion matrix in the segmentation code example (03_intro_image_classification/02_segment_ml_classification.ipynb) with the 'rsgislib.classification.classaccuracymetrics.calc_acc_metrics_vecsamples' method. How would the implementation be to show the confusion matrix?
