### ISSUE TITLE
Segmentation Runtime Error  

### ISSUE THREAD

**Issue by MrZombie69232** [remotesensinginfo/rsgislib#41]
Hi,
I was trying to run slic segmentation and got Runtime while doing so. Also, can we have segmentation with more than  3 bands ? 

My code : - 
`perform_slic_segmentation(
    input_img, 
    output_img,
    gdalformat='KEA', 
    no_data_val=0, 
    tmp_dir='tmp', 
    calc_stats=True,
    n_segments=125000, 
    compactness=0.1)` 

Error -
`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File <timed exec>:4, in <module>

File C:\ProgramData\Anaconda3\envs\rsgis\lib\site-packages\rsgislib\segmentation\skimgseg.py:445, in perform_slic_segmentation(input_img, output_img, gdalformat, no_data_val, tmp_dir, calc_stats, use_pca, n_pca_bands, pca_pxl_sample, n_segments, compactness, max_iter, sigma, spacing, convert_to_lab, enforce_connectivity, min_size_factor, max_size_factor, slic_zero)
    429 segResult = skimage.segmentation.slic(
    430     pxlVals,
    431     n_segments=n_segments,
   (...)
    441     slic_zero=slic_zero,
    442 )
    443 segResult = segResult + 1
--> 445 gdalOutDS = gdal.Open(output_img, gdal.GA_Update)
    446 gdalOutBand = gdalOutDS.GetRasterBand(1)
    447 gdalOutBand.WriteArray(segResult)

File C:\ProgramData\Anaconda3\envs\rsgis\lib\site-packages\osgeo\gdal.py:4580, in Open(*args)
   4578 def Open(*args):
   4579     """Open(char const * utf8_path, GDALAccess eAccess) -> Dataset"""
-> 4580     return _gdal.Open(*args)

RuntimeError: The HDF5ImageDataset driver does not support update access to existing datas`

Thanks for your help !

**Comment by petebunting** [comment]
Sorry I didn't reply to your earlier. Which file format are you using for input and output images? From the error it looks like you are using KEA and that your environment has a GDAL install without KEA being available. 

Did you install through conda-forge?

**Comment by MrZombie69232** [comment]
Hi,
Thank you for responding. 
I am using the tiff file as input and kea format as output. On the same image, shepherd segmentation worked well. 
I have installed the library through conda-forge 
Thank you for your help!

**Comment by MrZombie69232** [comment]
Hi @petebunting ,
No other segmentation works apart from shepherd segmentation. I am getting the same error.
I appreciate your help!
