### ISSUE TITLE
Pip compatibility

### ISSUE THREAD

**Issue by margaretharrison** [remotesensinginfo/rsgislib#55]
Hi folks - are there plans to make rsgislib pip compatible? Thanks!

**Comment by petebunting** [comment]
Hello, 

No, I do not plan to make a pip compatible install. The dependencies required, particularly for the c++ parts of rsgislib would make that really quite hard to do. We compile the library using the cmake tool. 

Builds are provided via conda-forge (conda install -c conda-forge rsgislib) for a wide variety of python versions and operating systems so I think that covers the majority of people's needs.

**Comment by margaretharrison** [comment]
Thanks Pete - good to know.

**Comment by cmosig** [comment]
I know you said there are no plans, but also I think pip support would be amazing. Many folks I know have never touched conda.
