### ISSUE TITLE
Divide by gamma?

### ISSUE THREAD

**Issue by cstutts** [remotesensinginfo/rsgislib#6]
Should you not be dividing by gamma instead of multiplying by it to match Shepherd's Equation 8?

https://github.com/remotesensinginfo/rsgislib/blob/1a90429b92e3effc559a8a0c5aa60f93eca87aa0/src/calibration/RSGISApply6SCoefficients.cpp#L773

**Comment by petebunting** [comment]
Sorry. It took me a long while to get to this. 

I've tested this and while the eq8 is divide by gamma when implemented in this form it does not standardise the topography but increases the topographic effect. While multiply reduces the effect. It maybe that I have reverse an angle or something else where.
