### ISSUE TITLE
morphological closing requirement

### ISSUE THREAD

**Issue by nmt28** [remotesensinginfo/rsgislib#60]
@petebunting Morphological closing provides an option to use a morph file. If set to False, a file still needs to be provided before the code will run. For example, this will not work:

	output_img = in_img.replace('.tif','_beta0_dB_Wmask_clump_close.kea')
	tmp_img = in_img.replace('.tif','_beta0_dB_Wmask_clump_close_tmp.kea')
	morph_op_file = None
	use_op_file = False
	op_size = 5
	gdalformat = "KEA"
	datatype = rsgislib.TYPE_16UINT
	niters = 1

while this will work:

	output_img = in_img.replace('.tif','_beta0_dB_Wmask_clump_close.kea')
	tmp_img = in_img.replace('.tif','_beta0_dB_Wmask_clump_close_tmp.kea')
	morph_op_file = '/morph_closing.txt'
	use_op_file = False
	op_size = 5
	gdalformat = "KEA"
	datatype = rsgislib.TYPE_16UINT
	niters = 1

probably just a catch needed on the use_op_file arg?

**Comment by petebunting** [comment]
Hi @nmt28 

Fair point. It could be tidier. I would pass an empty string rather than None and then it would work. Although, personally I would normally use a circular filter for the morphology which requires the file operator so I would usually be passing a file to the function.

Cheers, Pete

**Comment by nmt28** [comment]
ok, so perhaps some minor tidy up or some edits to the docs for clarity. I'll close out
