### ISSUE TITLE
Problem installing RSGISLIB

### ISSUE THREAD

**Issue by kolrocket** [remotesensinginfo/rsgislib#64]
Recently I tried to install RSGISLib via Windows 10 through Visual Code Studio, this version:
Version: 1.81.1 (user setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

 I followed your guide by typing:

conda create -n osgeo-env-v1 python=3.7
conda activate osgeo-env-v1 #changed from source activate osgeo-env-v1
conda install -c conda-forge rsgislib

But the installation got stuck here:
![image](https://github.com/remotesensinginfo/rsgislib/assets/43976033/17f91281-08f7-4154-8493-0f688e361048)

Any way to solve this?
Thank you very much

**Comment by petebunting** [comment]
I would suggest using python 3.10 (or 3.9 or 3.11) as conda-forge does not build for python 3.7 any more and therefore it will struggle (fail) to resolve the dependency tree. 

Many thanks, 

Pete
