### ISSUE TITLE
repo page links to dead https

### ISSUE THREAD

**Issue by dotysan** [remotesensinginfo/rsgislib#71]
https://github.com/remotesensinginfo/rsgislib links to https://www.rsgislib.org/ but it's not responding. Only http://www.rsgislib.org/ appears to be working at this time.

**Comment by petebunting** [comment]
I changed the server to https isn't available anymore but I cannot find the link on the page you are referring to they all look to be HTTP to me.

**Comment by dotysan** [comment]
Sorry I wasn't clear. On the main repo page on the right side under About.
![image](https://github.com/user-attachments/assets/57818787-65b0-44ca-9cc5-1a1f75d8f96a)
I think you should have a gear icon on your own repo to edit the link.

**Comment by petebunting** [comment]
Thanks - I hadn't noticed that one. Fixed now.
